import {
    PIPELINE_STAGES,
    RUN_STATUSES,
    TELEMETRY_RUN_TYPES,
} from "../../../shared/constants/telemetry.js";

import { bindCitations } from "../../retrieval/citation.service.js";
import { startTelemetryRun } from "../../telemetry/services/telemetryRecorder.service.js";
import { answerQuestion } from "./answer.service.js";
import { generateAnswer } from "./generation.service.js";
import { routeQuery } from "./routing.service.js";

/**
 * Handles one natural-language question from the browser.
 *
 * Two paths are supported:
 *
 * 1. Explicit evidence path
 *    Used by TENISE-19 control tests and TENISE-30 telemetry tests.
 *    Evidence is supplied directly, so real retrieval is skipped.
 *
 * 2. Normal application path
 *    Uses answerQuestion(), which owns the real plan -> retrieve ->
 *    compose -> verify flow, including retrieval, role filtering,
 *    grounding and citation handling.
 *
 * roleId deliberately has no default. In production it must come from
 * the authenticated session rather than from a value selected by the client.
 */
export async function submitChatQuestion(
    question,
    {
        evidence = null,
        correlationId = null,
        roleId,
        telemetryRun = null,
    } = {},
) {
    /*
     * Do not silently fall back to admin.
     *
     * A missing role is an authentication / request-context problem and
     * should be surfaced rather than granting maximum access.
     */
    if (!roleId || String(roleId).trim() === "") {
        throw new Error(
            "submitChatQuestion requires a roleId. There is no default role on purpose.",
        );
    }

    /*
     * Explicit evidence is used by grounding and telemetry tests.
     *
     * `[]` still counts as supplied evidence, which is important for
     * tests that deliberately provide an empty evidence set.
     */
    if (evidence !== null) {
        return answerFromSuppliedEvidence(
            question,
            evidence,
            roleId,
            {
                correlationId,
                telemetryRun,
            },
        );
    }

    /*
     * Normal browser path.
     *
     * answerQuestion() owns the full production-style query pipeline so
     * the browser and CLI share the same retrieval and citation behaviour.
     */
    const result = await answerQuestion(
        question,
        {
            roleId,
            correlationId,
        },
    );

    return {
        status: "completed",

        response: {
            answer: result.answer,
            receivedQuestion: question,
            answered: result.answered,
            evidenceCount: result.citations.length,
            intent: result.intent,
            route: result.route,

            /*
             * Structured query fields are only populated when applicable.
             */
            table: result.table ?? null,
            data: result.data ?? null,
            sql: result.sql ?? null,

            grounding: result.grounding,
            retrieval: result.telemetry,
        },

        citations: result.citations,
    };
}

/**
 * Handles requests where evidence is deliberately supplied by the caller.
 *
 * Real retrieval does not run on this path because the evidence has already
 * been provided. Citation markers generated by the model are still bound back
 * to those supplied evidence chunks.
 */
async function answerFromSuppliedEvidence(
    question,
    evidence,
    roleId,
    {
        correlationId = null,
        telemetryRun = null,
    } = {},
) {
    /*
     * Normalise evidence defensively so downstream generation and
     * citation binding always receive an array.
     */
    const suppliedEvidence =
        Array.isArray(evidence)
            ? evidence
            : [];

    const run =
        telemetryRun ||
        startTelemetryRun({
            runType: TELEMETRY_RUN_TYPES.QUERY,
            correlationId,
        });

    try {
        /*
         * Record the query class for TENISE-30 telemetry.
         */
        const routing = await routeQuery({
            question,
            recorder: run,
        });

        /*
         * Retrieval is intentionally skipped because the caller supplied
         * the evidence directly.
         */
        run.skipStage(
            PIPELINE_STAGES.RETRIEVAL,
            "evidence_supplied_by_caller",
        );

        const generation = await generateAnswer({
            question,
            evidence: suppliedEvidence,
            recorder: run,
        });

        /*
         * Bind markers such as [1] back to the actual supplied chunks.
         */
        const bound = bindCitations(
            generation.answer,
            suppliedEvidence,
        );

        await run.finish(
            RUN_STATUSES.SUCCESS,
        );

        return {
            status: "completed",

            response: {
                answer: generation.answer,
                receivedQuestion: question,
                answered: true,
                evidenceCount: suppliedEvidence.length,

                queryClass: routing.queryClass,
                intent: "caller_supplied_evidence",
                route: "unstructured",

                generation: {
                    model: generation.model,
                    promptVersion: generation.promptVersion,
                },

                grounding: {
                    grounded: bound.grounded,
                    danglingCitations: bound.dangling,
                    abstained: false,
                },

                retrieval: {
                    role: roleId,
                    queryKind: "caller_supplied_evidence",
                },
            },

            citations: bound.citations,

            /*
             * Allows the caller to retrieve the completed telemetry record.
             */
            telemetry: {
                recordId: run.recordId,
            },
        };
    } catch (error) {
        run.fail(error);

        await run.finish(
            RUN_STATUSES.FAILED,
        );

        throw error;
    }
}